const AIDEN_TRUST_ADMIN_THEME_VARIANT_KEY = 'AIDEN_TRUST_ADMIN_THEME_VARIANT_KEY';
const SERVER_BASE_URL = 'SERVER_BASE_URL';

export const CONSTANTS = {AIDEN_TRUST_ADMIN_THEME_VARIANT_KEY, SERVER_BASE_URL};
